### ISSUE TITLE
Cleanup code: phase 1

### ISSUE THREAD

**Issue by MaceKuailv** [MaceKuailv/seaduck#37]
- [x] Change the register weight function thing mentioned in issue #16 
- [x]  #33 
- [x] #34 
- [x] Use `itertools` and `collections`. #35 
- [x] Reduce one dimensional index operations. #36 
- [x] Read through the code a few more time, do other stuff to increase the readability.

**Comment by malmans2** [comment]
About the first bullet point: If you are thinking to add comments to the code, that's not always a good idea. 

Docstrings are great because they serve as documentation.

But if you fell that you also need to add in-line comments to your code, that probably means that the code is not very clear or readable. Inline comments should be used sporadically, mainly for edge cases or TODOs.

**Comment by MaceKuailv** [comment]
OK, I will try making things readable first.

**Comment by MaceKuailv** [comment]
Resolved with PR https://github.com/MaceKuailv/seaduck/pull/38
